# docker-compose.yml
# author: Seong Yong-ju <sei40kr@gmail.com>
---
version: "3"
services:
  web:
    image: sei40kr/friendlyhello
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
